spring.application.name=intern-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/intern_demo
spring.datasource.username=postgres
spring.datasource.password=shovon
spring.jpa.hibernate.ddl-auto=update
